Repository pygame-guide-for-sneks/pygame-guide-for-sneks.github.io, pull requests merged in 2022-12, with the labels that each got.

#64 edited javascript to right-align line numbers
  scripts/format.js
Labels: PR: Awaiting merge

#59 described all ways to create a color
  intro/fonts/index.html
Labels: PR: Needs re-review, PR%3A%20Needs%20first%20approval, PR%3A%20Needs%20second%20approval

#65 Add 404, move CSS files, change buttons, misc changes
  404.html
  _includes/footer.html
  _layouts/default.html
  assets/404_pg_sad.png
  assets/css/main.css
  assets/css/onedark.css
  assets/css/style.scss
  index.html
Labels: PR: Needs second approval

#66 Add tailwind support
  .gitignore
  Gemfile
  Gemfile.lock
  _config.yml
  assets/css/style.scss
  documentation/contributing.md
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
Labels: PR: Needs second approval

#46 Classes
  intro/classes/index.html
Labels: PR: Needs first approval
