Repository pygame-guide-for-sneks/pygame-guide-for-sneks.github.io, pull requests merged in 2023-02, with the labels that each got.

#81 massive reorganization
  _layouts/default.html
  assets/favicon.ico
  assets/logo_files/logo.svg
  assets/logo_files/logo_scale_1.png
  assets/logo_files/logo_scale_2.png
  assets/logo_files/logo_scale_5.png
  cypress/pages/classPage.js
  cypress/pages/fontPage.js
  cypress/pages/homePage.js
  cypress/pages/setupPage.js
  documentation/template.html
  guide/404.html
  guide/intro/audio/index.html
  guide/intro/classes/index.html
  guide/intro/colors/index.html
  guide/intro/fonts/index.html
  guide/intro/images/index.html
  guide/intro/moving-things/index.html
  guide/intro/platformer/index.html
  guide/intro/setup/index.html
  guide/intro/shapes/index.html
  guide/obscure/blend-modes/index.html
  guide/obscure/pixelarray/index.html
  guide/obscure/set-mode-flags/index.html
  guide/scripts/format.js
  index.html
  postcss.config.js
Labels: PR: Needs second approval

#80 added CREDITS.md, updated README.md
  README.md
  documentation/CREDITS.md
Labels: Documentation, PR: Needs second approval

#98 Splitting CI into separate browsers
  .github/workflows/chrome_ci.yml
  .github/workflows/electron_ci.yml
Labels: PR: Awaiting merge

#100 remapped pgex to new location
  _includes/footer.html
Labels: PR: Awaiting merge
